Update Rasplex, PlexBlack, Recalbox and noobs
LaurentMarchelli/recalbox-rasplex pull request #15
Opened 2017-04-08 13:04 UTC by Eloo

Update to latest versions and use noobs lite for faster build.

2017-04-08 16:13 UTC, LaurentMarchelli requested changes
Hi Joseph,

Thank for your help, I had to do it, you made my day.
I guess you had some trouble with my master merge, so there are some duplicate codes.

Could you please, check requested corrections.
Thank's,

Laurent

2017-04-08 16:13 UTC, LaurentMarchelli commented on package/noobs/noobs.mk
> +NOOBS_VERSION = v2_3
I guess you have checked it works with the light version right ?

2017-04-08 16:13 UTC, LaurentMarchelli commented on package/rasplex/Config.in
> +    bool "1.7.1 - Stable"
Last Stable is 1.6.2 ... 1.7.1 is still pre-release.
Furthermore, your rasplex.mk file does it right it uses the 1.6.2 ... ;-)

2017-04-08 16:13 UTC, LaurentMarchelli commented on package/rasplex/rasplex.mk
> +################################################################################
Why these duplicate lines, there were already defined lines 35 - 43 ?
I guess it is a merge conflict error.

2017-04-08 16:13 UTC, LaurentMarchelli commented on package/rasplex/rasplex.mk
> +		$(RASPLEX_TAR_BUILD)/plexdata/.recalplex/;
Why these duplicate lines, there were already defined lines 137 - 168 ?
I guess it is a merge conflict error.

2017-04-08 16:13 UTC, LaurentMarchelli commented on package/rasplex/rasplex.mk
> +		RASPLEX_SKIN_VERSION = 17.03.16
It shouldn't be 18.x.x for the version 18, could you please check.

2017-04-08 16:13 UTC, LaurentMarchelli commented on package/rasplex/rasplex.mk
> +
Old code, now we are downloading the skin from the official source https://addons.openpht.tv/openpht-1.8, not from https://goo.gl anymore.
I guess it is a merge conflict error.

2017-04-08 16:13 UTC, LaurentMarchelli commented on package/recalboxOS/recalboxOS.mk
> +else ifeq ($(BR2_PACKAGE_RECALBOXOS_UNSTABLE),y)
Extra download is not needed for the stable, as the boot.tar.xz and the root.tar.xz are already included in the zip file.
Following line is enough to replace your block.
ifeq ($(BR2_PACKAGE_RECALBOXOS_UNSTABLE),y)

2017-04-09 17:28 UTC, Eloo commented on package/rasplex/rasplex.mk
> +		RASPLEX_SKIN_VERSION = 17.03.16
its a timestamp ;) so the 17 stands for 2017

2017-04-09 17:29 UTC, Eloo commented
Hi Laurent, yes I was facing some trouble while merging.. 
I will recheck the changes in time.

2017-04-16 05:48 UTC, LaurentMarchelli commented
Hi Joseph,
Do you need some help to resync ?
Regards,
Laurent

2017-04-17 14:19 UTC, LaurentMarchelli commented
Hi Joseph,

Your changes have been checked and merged with #18, please resynchronize your fork.
Try to avoid working on master branch, as it is your repository default branch, github does not allows the push force.
Using pull -r (rebase) on a development branch is always better than merging.
Thank for your contribution, noobs lite version save bandwidth.

Best regards,
Laurent Marchelli

2017-04-17 14:19 UTC, closed without merging

2017-04-18 06:45 UTC, Eloo commented
Hi Laurent,

glad to see you've already adapted my changes.
Sorry that i cant fix my PR but I was busy last weeks. 
Okay yes will try to work on feature branche in future ;)
Is there a special reason why you are using noobs lite 2.1 instead of 2.3?

Best regards,
Joseph

2017-04-18 07:29 UTC, LaurentMarchelli commented
Hi Joseph,

No problem, when I didn't see any answer I guessed you were busy and as I could handle it ... It's the way a team works, isn't it ? ;-)

I downgraded noobs to version 2.1 because there is a bug since version 2.2, Noobs does not take care of autoboot.txt, so you get the noobs boot menu each time you try to switch, check my commit comment :
Noobs_lite version 2_3 does not work with autoboot.txt raspberrypi/noobs#390

In another hand, because I changed the url of the .buildroot submodule, you may have trouble to resync your fork, so let me know if you need any help to resync and clean your master branch.

Best regards,
Laurent Marchelli

2017-04-18 08:20 UTC, Eloo commented
Okay.. yeah may i will remove my fork and re-fork next time i will contribute.. i guess this is the best solution to work on a clean tree ;)

2017-04-18 08:30 UTC, LaurentMarchelli commented
As u like, : 
- Creating a new fork is easier and faster.
- Resynchronizing your fork may be harder, but may learn more.
Let me know. ;-)

Best Regards,
Laurent Marchelli